Added L4 IT MOp
obophenotype/cell-ontology pull request #1011
Opened 2021-03-22 15:33 UTC by shawntanzk

Fixes #884
- Requires some input on what goes in/stays out, see ticket #884 for details.
- Not sure if morphological description is useful in this case too (given diverse morphologies)

2021-03-22 20:43 UTC, patrick-lloyd-ray approved these changes

2021-03-26 16:28 UTC, dosumis requested changes
Hold off merging until further discussion (please see comment)

2021-03-26 16:28 UTC, dosumis commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:33184512") obo:IAO_0000115 obo:CL_4023051 "An intratelencephalic-projecting glutamatergic neuron that is located in the boundary between L2/3 a
This strikes me as a heterogenous grouping class that only makes sense in the context of single cell transcriptomics clustering.  I wonder whether we should make that explicit + define using markers (RF markers could work well for this).  I think worth holding off for further discussion.

2021-12-09 17:25 UTC, shawntanzk commented
migrated to https://github.com/obophenotype/brain_data_standards_ontologies/issues/226

2021-12-09 17:25 UTC, closed without merging