Edit L5 ET Synonyms
obophenotype/cell-ontology pull request #1153
Opened 2021-06-29 07:38 UTC by shawntanzk

***DRAFT***

Fixes #1147

2021-06-29 09:16 UTC, dosumis requested changes
See comments

2021-06-29 09:16 UTC, dosumis commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "DOI:10.1016/j.neuron.2005.08.030") oboInOwl:hasExactSynonym obo:CL_4023041 "subcerebral projection (SCPN) neuron")
I think this one should be a broad synonym:
![image](https://user-images.githubusercontent.com/112839/123770800-7ac64000-d8c2-11eb-974e-4606d235760c.png)

2021-06-29 09:16 UTC, dosumis commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "DOI:10.1038/nrn3469") oboInOwl:hasExactSynonym obo:CL_4023041 "pyramidal tract (PT) neuron")
Given comment on pyramidal-tract like - this should probably be a narrow synonym.

2021-06-29 10:08 UTC, shawntanzk commented
Made the changes, also changed L5b neuron to broad synonym as L5b is defined by PT neurons instead of L5b neuron being PT neurons I think

2021-07-02 18:42 UTC, patrick-lloyd-ray approved these changes

2021-07-21 10:36 UTC, merged