Update README.md
obophenotype/cell-ontology pull request #1756
Opened 2022-12-01 15:57 UTC by dosumis

Updating documentation links

2022-12-02 07:45 UTC, shawntanzk requested changes

2022-12-02 07:45 UTC, shawntanzk commented on README.md
> +- [https://cell-ontology.github.io/](CL Website)
```suggestion
- (CL Website)[https://cell-ontology.github.io/]
```

2022-12-02 07:45 UTC, shawntanzk commented on README.md
> +* Generic ODK workflows [src/ontology/README-editors.md](src/ontology/README-editors.md)
```suggestion
* [Generic ODK workflows](src/ontology/README-editors.md)
```

2022-12-06 13:06 UTC, bvarner-ebi commented on README.md
> +- [https://cell-ontology.github.io/](CL Website)
```suggestion
- [CL Website](https://cell-ontology.github.io/)
```

2022-12-06 13:09 UTC, bvarner-ebi commented on README.md
> +* [CL Editor doc](https://obophenotype.github.io/cell-ontology/.)
```suggestion
* [CL Editor doc](https://obophenotype.github.io/cell-ontology/)
```

2022-12-06 13:10 UTC, bvarner-ebi requested changes
Suggestions added

2022-12-06 15:58 UTC, bvarner-ebi approved these changes

2022-12-06 15:59 UTC, dosumis commented on README.md
> +- [https://cell-ontology.github.io/](CL Website)
Syntax wrong.  Have fixed directly.

2022-12-07 08:49 UTC, shawntanzk approved these changes

2022-12-07 08:50 UTC, merged