SOP to create slims
obophenotype/cell-ontology pull request #2068
Opened 2023-07-17 13:43 UTC by aleixpuigb

Addresses #1919 to write an SOP for editors adding new upper-level slims or extending existing ones, & integrate this into the developers manual.

2023-07-17 16:50 UTC, anitacaron requested changes

2023-07-18 09:28 UTC, aleixpuigb commented on docs/Create_upper_level_slim.md
> +     ![image](https://github.com/obophenotype/cell-ontology/assets/94959119/4673253e-9526-43b4-8608-8d7e7b27d988)
Done, thank you!

2023-07-18 09:28 UTC, aleixpuigb commented on docs/Create_upper_level_slim.md
> +- Create a CSV table with the following characteristics (Find examples in [src/templates](https://github.com/obophenotype/cell-ontology/tree/master/src/templates)):
Done!

2023-07-18 09:34 UTC, anitacaron approved these changes

2023-07-18 11:57 UTC, aleixpuigb commented on docs/Create_upper_level_slim.md
> +- Create XXX_upper_slim in Protege (change "XXX" to the subset label). [See *Adding a new Subset*](https://oboacademy.github.io/obook/howto/add-new-slim/).
Yes, the creation of slim is the same, but the addition of terms is different.

2023-07-18 14:19 UTC, merged