Addresses #2144 NTR 'airway submucosal gland duct ciliated cell'
obophenotype/cell-ontology pull request #2145
Opened 2023-09-08 10:48 UTC by aleixpuigb

Addresses #2144 NTR 'airway submucosal gland duct ciliated cell'

2023-09-08 10:53 UTC, aleixpuigb commented
#gogoeditdiff

2023-09-11 13:06 UTC, bvarner-ebi commented on src/ontology/cl-edit.owl
> +EquivalentClasses(obo:CL_4033055 ObjectIntersectionOf(obo:CL_0000064 ObjectSomeValuesFrom(obo:BFO_0000050 obo:UBERON_8600014)))
"airway" is noted in label and text definition, but this association is missing from the logical definition.

2023-09-11 13:21 UTC, bvarner-ebi requested changes
Please see inline comment.

2023-09-11 14:11 UTC, bvarner-ebi approved these changes

2023-09-11 14:30 UTC, merged