Update README.md
obophenotype/cell-ontology pull request #2215
Opened 2023-11-02 14:23 UTC by dosumis

2023-11-02 16:25 UTC, aleixpuigb requested changes
Please, consider the suggested changes.

2023-11-02 16:25 UTC, aleixpuigb commented on README.md
> +The Cell ontology is used to annotate cell types on the single cell transcriptomics platform CellxGene.  All datasets on CellXGene are annotated according to a standard schema that specifies use of C
```suggestion
The Cell ontology is used to annotate cell types on the single cell transcriptomics platform CellxGene.  All datasets on CellXGene are annotated according to a standard schema that specifies the use of CL to record Cell Type.  Uses in CellXgene tools:
```

2023-11-02 16:25 UTC, aleixpuigb commented on README.md
> + - In [CellGuide](https://cellxgene.cziscience.com/cellguide) CL term names and synonyms drive search,  terms are used to structure the guide and ontology structure support a graphical browser
I am not sure I am undestanding this sentence correctly, but as I understand it:
 - In [CellGuide](https://cellxgene.cziscience.com/cellguide), CL term names and synonyms drive search  Terms are used to structure the guide, and the ontology structure supports a graphical browser.

2023-11-03 09:28 UTC, dosumis commented
Fixed (Just realised I could have accepted your suggestions, but dit them by hand instead).

2023-11-03 09:42 UTC, aleixpuigb requested changes
There is an extra closing parenthesis, but everything else looks good. Once you push the commit I will approve the PR.

2023-11-03 09:42 UTC, aleixpuigb commented on README.md
> + - In the [Discover](https://cellxgene.cziscience.com/)) tool, the structure of CL is used to drive faceted searching for datasets and collections by Cell Type.
```suggestion
 - In the [Discover](https://cellxgene.cziscience.com/) tool, the structure of CL is used to drive faceted searching for datasets and collections by Cell Type.
```

2023-11-03 10:58 UTC, aleixpuigb approved these changes

2023-11-10 18:03 UTC, merged