NTR dermal chromatophore
obophenotype/cell-ontology pull request #2308
Opened 2024-03-07 09:44 UTC by paulacalipho

fixes #2307

2024-03-18 13:46 UTC, aleixpuigb requested changes
Thank you for submitting the PR.
Please, consider the suggested changes.

2024-03-18 18:09 UTC, dosumis commented on src/ontology/cl-edit.owl
> +SubClassOf(obo:CL_4040006 obo:CL_0000147)
I think it is good as it is.  A logical def with these axioms would be much too broad.

2024-03-19 06:22 UTC, paulacalipho commented
@aleixpuigb @dosumis Thank you for reviewing. I get this warning, and I do not understand what it means and what I should do
![image](https://github.com/obophenotype/cell-ontology/assets/4089751/112de90a-f999-4e6f-b6e2-cc20ee876012)

2024-03-19 09:21 UTC, anitacaron commented
@paulacalipho, no worries. It's just a difference between Operational Systems and how they interpret the line ending in the file.

2024-03-19 13:46 UTC, paulacalipho commented
@aleixpuigb I understood I did not need to do the logical definition, right? Is there anything else to improve?

2024-03-19 13:55 UTC, aleixpuigb approved these changes
>@aleixpuigb I understood I did not need to do the logical definition, right? Is there anything else to improve?

That's correct, the logical definition is not needed. Everything looks good, thank you!

2024-03-19 15:58 UTC, paulacalipho commented
@aleixpuigb thanks, It is indicated merging is blocked. Could you do it for me?

2024-03-19 16:06 UTC, merged