Update relations_guide.md
obophenotype/cell-ontology pull request #2364
Opened 2024-04-30 10:54 UTC by dosumis

Fixes #2362

2024-04-30 14:39 UTC, JABelfiore approved these changes

2024-04-30 14:49 UTC, aleixpuigb requested changes
Please, see inline comments

2024-04-30 14:49 UTC, aleixpuigb commented on docs/relations_guide.md
> +To record which neurotransmitter a neuron releases, use a [**'capable of'**](http://purl.obolibrary.org/obo/RO_0002215) relation to link the neuron to a  to a subclass of GO [neurotransmitter secreti
```suggestion
To record which neurotransmitter a neuron releases, use a [**'capable of'**](http://purl.obolibrary.org/obo/RO_0002215) relation to link the neuron to a subclass of GO [neurotransmitter secretion](http://purl.obolibrary.org/obo/GO_0007269).  This should be sufficient for autoclassification.
```

2024-04-30 14:49 UTC, aleixpuigb commented on docs/relations_guide.md
> +[**'capable of'**](http://purl.obolibrary.org/obo/RO_0002215)
It's repeated, might have been pasted duplicated.

2024-04-30 14:49 UTC, aleixpuigb commented on docs/relations_guide.md
> +### Recording neurotransmitter for neurons
I think this could be a subsection of **capable of**.

2024-04-30 14:49 UTC, aleixpuigb commented on docs/relations_guide.md
> +[**'capable of'**](http://purl.obolibrary.org/obo/RO_0002215)
It looks like it is missing an example here. e.g.
'GABAergic neuron' 'capable of' some 'gamma-aminobutyric acid secretion, neurotransmission'

2024-05-02 17:36 UTC, dosumis commented
@JABelfiore - I think I've addressed the issues.  @aleixpuigb  is away (AFAIK).  Could you review changed and approve if OK?

2024-05-03 08:16 UTC, JABelfiore approved these changes

2024-05-03 08:17 UTC, JABelfiore approved these changes

2024-05-03 09:08 UTC, anitacaron approved these changes

2024-05-03 09:08 UTC, merged