fenestrated capillary endothelial cells updates
obophenotype/cell-ontology pull request #2475
Opened 2024-08-06 11:20 UTC by Caroline-99

Updated logical and textual defs for peritubular capillary endothelial cells and subclasses 
- added logical defs
- Updated the textual defs and included references
- added extra description in the comments section

2024-08-06 13:10 UTC, Caroline-99 commented
This could be a separate ticket but I think glomerular endothelial cell should be merged into glomerular capillary endothelial cell as they both refer to the exact same cell type as ( same specialized endothelial cells found in the glomerular capillaries of the kidney). And glomerular endothelial cell could be added as a synonym?

2024-08-09 13:30 UTC, aleixpuigb commented
#gogoeditdiff

2024-08-09 13:33 UTC, aleixpuigb commented
#gogoeditdiff

2024-08-13 08:21 UTC, aleixpuigb reviewed
I would suggest to use 'that is part of' instead of 'found in'.

2024-08-13 09:02 UTC, Caroline-99 commented
> I would suggest to use 'that is part of' instead of 'found in'.

Done

2024-08-15 14:01 UTC, aleixpuigb requested changes
Please, see inline comments

2024-08-15 14:01 UTC, aleixpuigb commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(obo:IAO_0000115 obo:CL_1001123 "An endothelial cell that is part of the peritubular capillaries of the outer renal medulla.")
the peritubular capillaries should be singular, 'a peritubular capillary'.

2024-08-15 14:01 UTC, aleixpuigb commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(obo:IAO_0000115 obo:CL_1001124 "An endothelial cell that is part of the peritubular capillaries of the renal cortex.")
Same comment than above

2024-08-16 08:33 UTC, aleixpuigb commented on src/ontology/cl-edit.owl
> +Declaration(Class(obo:GO_0036053))
Can you also add this term in the GO imports txt file? I will refresh the imports later.

2024-08-16 08:57 UTC, aleixpuigb approved these changes

2024-08-16 09:02 UTC, merged