Re-done-t-type-GABAergic-VIP-cortical-interneuron-definition
obophenotype/cell-ontology pull request #2506
Opened 2024-08-19 13:26 UTC by AvolaAmg

fixes #2256

To follow changes in this PR, read @AmgAvola comments in the ticket #2256

Alpha1,2 Beta1,2 tanycyte added with definition, references, synonyms and logical definition.

2024-08-20 14:06 UTC, AvolaAmg commented on src/ontology/cl-edit.owl
> +SubClassOf(obo:CL_4042017 ObjectSomeValuesFrom(obo:BFO_0000050 obo:UBERON_0004642))
has_soma_location should be only to neurons right? 
this refers to 'part_of' and in the case of alpha1 tanycyte the anatomical part of the 'third ventricle ependyma'
alpha2 is in the 'arcuate nucleus of hypothalamus' 
beta1 and beta2 are in the 'infundibular recess of 3rd ventricle'
Do you mean I should have all of the in the 'third ventricle ependyma? 
thank you!

2024-08-20 14:07 UTC, AvolaAmg commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:16344112") Annotation(oboInOwl:hasDbXref "PMID:26578855") Annotation(oboInOwl:hasDbXref "PMID:29351662") Annotation(oboInOwl:hasDbXref "Wikiped
they express FGFR1 in all of the beta1 tanycytes and beta 2 tanycytes (from literature evidence)

2024-08-20 14:07 UTC, AvolaAmg commented on src/ontology/cl-edit.owl
> +Declaration(Class(obo:PR_000007479))
thank you!

2024-08-20 14:39 UTC, aleixpuigb commented on src/ontology/cl-edit.owl
> +SubClassOf(obo:CL_4042017 ObjectSomeValuesFrom(obo:BFO_0000050 obo:UBERON_0004642))
That is correct, it should be used in neurons. But your textual definition uses this terminology:
"A tanycyte cell that has its soma located in the ventromedial and dorsomedial nuclei of the hypothalamus."
Probably the definition should be amended.

2024-08-20 14:47 UTC, AvolaAmg commented on src/ontology/cl-edit.owl
> +SubClassOf(obo:CL_4042017 ObjectSomeValuesFrom(obo:BFO_0000050 obo:UBERON_0004642))
my mistake I will correct this, did not even notice I did that thank you!

2024-08-20 14:54 UTC, aleixpuigb approved these changes

2024-08-20 14:54 UTC, aleixpuigb requested changes
The branch has conflicts.

2024-08-21 11:19 UTC, merged

2024-09-23 11:37 UTC, dosumis commented
#gogoeditdiff (not sure if this will work once closed, but trying as will be useful for me grok details of changes)