NTR-astrocyte-restricted-precursor-and-neuronal-restricted-precursor
obophenotype/cell-ontology pull request #2512
Opened 2024-08-21 11:39 UTC by AvolaAmg

fixes #2437 #2435

2024-08-23 15:23 UTC, Caroline-99 commented
#gogoeditdiff

2024-09-02 11:54 UTC, AvolaAmg commented
#gogoeditdiff

2024-09-03 07:57 UTC, Caroline-99 requested changes

2024-09-16 10:23 UTC, AvolaAmg commented on src/ontology/cl-edit.owl
> +
unsure on the neuroepithelial development so I would not mention it

2024-09-16 15:11 UTC, Caroline-99 commented
#gogoeditdiff

2024-09-16 15:36 UTC, Caroline-99 commented
everything looks good

2024-09-16 15:39 UTC, merged