NTR pthlh-expressing interneuron for Basal Ganglia BICAN
obophenotype/cell-ontology pull request #2569
Opened 2024-09-17 10:32 UTC by AvolaAmg

Fixes #2568

2024-09-17 11:17 UTC, dosumis commented
#gogoeditdiff

2024-09-17 11:41 UTC, dosumis requested changes
See comments in-line

2024-09-17 11:41 UTC, dosumis commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(rdfs:label obo:CL_4042023 "pthlh-expressing interneuron"@en)
Should the name be more specific?  e.g. include striatal

2024-09-17 11:41 UTC, dosumis commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:30134177") Annotation(oboInOwl:hasDbXref "PMID:37292997") obo:IAO_0000115 obo:CL_4042023 "A GABAergic interneuron that has its soma in a striat
This reads like it covers all GABAergic neurons in the striatum.  

proposed change to 

A PTHLH expressing GABAergic neuron with its soma in the striatum.  

IS PVALB really expressed in all?
![image](https://github.com/user-attachments/assets/6635b706-7038-497e-896a-e816b1f3cb3b). Maybe mention spatial gradient of PVALB across these cells in the gloss?

2024-09-17 11:41 UTC, dosumis commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:37292997") oboInOwl:hasRelatedSynonym obo:CL_4042023 "PTHLH/PVALB cell")
See notes on PVALB. Ditto for other synonyms.

2024-09-17 11:41 UTC, dosumis commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:35308118") obo:IAO_0000115 obo:CL_4042024 "A pthlh-expressing interneuron that expresses MOXD1.")
Wrong ref? Looks like different neuron types covered. Don't seem pthlh or MOXD1 in this paper

2024-09-17 11:52 UTC, dosumis commented on src/ontology/cl-edit.owl
> +# Class: obo:CL_4042023 (pthlh-expressing interneuron)
DANGER Clashing ID with edit in  https://github.com/obophenotype/cell-ontology/pull/2566/files !!!!

2024-09-17 12:51 UTC, hkir-dev commented
I am testing #gogoeditdiff command here. I will delete this comment afterwards.

2024-09-17 14:23 UTC, AvolaAmg commented
@dosumis addressed

2024-09-17 19:22 UTC, dosumis commented
#gogoeditdiff

2024-09-19 13:24 UTC, dosumis reviewed
This is too broad:
[striatal pthlh-expressing interneuron](http://purl.obolibrary.org/obo/CL_4042023) [has_related_synonym](http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym) "pvalb-expressing cell"

Also better to have some detail on location in text def of MOXD1 neuron even if redundant.  Otherwise potentially too sparse for most users to appreciate what it refers too.

2024-09-23 10:35 UTC, AvolaAmg commented
#gogoeditdiff

2024-09-24 11:35 UTC, dosumis approved these changes

2024-09-24 11:46 UTC, merged