Fixes #2578 -NTR- fibroblastic reticular cell
obophenotype/cell-ontology pull request #2581
Opened 2024-09-19 11:32 UTC by Caroline-99

- Added a new term
- Added textual and logical definition with extended description
- Added synonyms
- Added references

2024-09-19 11:41 UTC, Caroline-99 commented
#gogoeditdiff

2024-09-20 12:28 UTC, aleixpuigb requested changes
Please, see inline comments.

2024-09-20 12:34 UTC, dosumis commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(rdfs:comment "doi:/10.1038/s41467-022-29734-2") oboInOwl:hasNarrowSynonym obo:CL_4052004 "solitary intestinal lymphoid tissue (SILT) FRCs")
What's wrong with abbvs in synonyms?  Didn't realise we had a policy against that.

2024-09-20 12:36 UTC, dosumis commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:33707780") Annotation(oboInOwl:hasDbXref "doi:/10.1038/s41467-022-29734-2") obo:IAO_0000115 obo:CL_4052004 "A specialized fibroblastic reticula
I agree that abbreviations should not be used on there own, but I don't see a problem with including the abbreviation in brackets after the full terms.   The vast majority of the literature uses GALT, so I think important for users to see this.

2024-09-20 12:36 UTC, aleixpuigb commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(rdfs:comment "doi:/10.1038/s41467-022-29734-2") oboInOwl:hasNarrowSynonym obo:CL_4052004 "solitary intestinal lymphoid tissue (SILT) FRCs")
Abbreviations are fine, however I was told that they should be a separate synonym with the AP has_synonym_type 'abbreviation.

2024-09-23 14:12 UTC, aleixpuigb approved these changes

2024-09-23 14:13 UTC, merged