Fixes #2586 NTR-enteroendocrine progenitor
obophenotype/cell-ontology pull request #2588
Opened 2024-09-20 12:25 UTC by Caroline-99

Added a new term with textual and logical defs, synonyms and references

2024-09-23 13:35 UTC, dosumis commented
#gogoeditdiff

2024-09-23 15:00 UTC, Caroline-99 commented
#gogoeditdiff

2024-09-24 09:26 UTC, aleixpuigb requested changes
Please, see inline comments.

2024-09-24 09:26 UTC, aleixpuigb commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:31756561") Annotation(oboInOwl:hasDbXref "PMID:32531023") Annotation(oboInOwl:hasDbXref "PMID:35913117") Annotation(oboInOwl:hasDbXref "PMID:38
> In mouse and human, it expresses markers like Neurog3

This is a bit informal consider alternative formulas:
- In mouse and human, this cell expresses Neurog3
- In mouse and human, this cell can be characterized by the expression of Neurog3
- In mouse and human, this cell expresses the marker Neurog3

2024-09-24 09:26 UTC, aleixpuigb commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:31756561") Annotation(oboInOwl:hasDbXref "PMID:32531023") Annotation(oboInOwl:hasDbXref "PMID:35913117") Annotation(oboInOwl:hasDbXref "PMID:38
I am super picky here, but instead of 'various' I would use 'multiple' or 'a range of'.

2024-09-24 09:26 UTC, aleixpuigb commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:31756561") Annotation(oboInOwl:hasDbXref "PMID:32531023") Annotation(oboInOwl:hasDbXref "PMID:35913117") Annotation(oboInOwl:hasDbXref "PMID:38
In the sentence:
> Its proliferative potential supports both crypt growth and cell proliferation, ...

What does it mean that the proliferative potential supports cell proliferation? I am not sure if it is its own proliferation or other cells, but in any case I would remove.

2024-09-24 09:51 UTC, aleixpuigb approved these changes

2024-09-24 09:52 UTC, merged