Fixes #2602 NTR granulosa cells and remake class hierarchy
obophenotype/cell-ontology pull request #2608
Opened 2024-09-24 13:40 UTC by aleixpuigb

Fixes #2602 NTR granulosa cells and remake class hierarchy

2024-09-24 13:40 UTC, aleixpuigb commented
#gogoeditdiff

2024-09-25 11:10 UTC, Caroline-99 requested changes

2024-09-25 11:10 UTC, Caroline-99 commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:28892263") obo:IAO_0000115 obo:CL_4033083 "A granulosa cell that has a squamous morphology and form a single layer around the oocyte in primord
I would suggest adding this " A granulosa cell that has a squamous morphology and form a single layer around the oocyte in primordial follicles. This cell develops directly into a cuboidal granulosa cell during the primordial-to-primary follicle transition."

2024-09-25 11:10 UTC, Caroline-99 commented on src/ontology/cl-edit.owl
> +SubClassOf(obo:CL_4033067 ObjectSomeValuesFrom(obo:RO_0002207 obo:CL_4033084))
I would also suggest modifying the textual definition to align with the new logical definition (ie. A follicular cell of ovary that differentiates from a **cuboidal** granulosa cell during the secondary follicle stage. Mural granulosa cells line the inner surface of the follicle wall, surrounding the fluid-filled antral cavity. These cells produce oestrogen during the follicular phase in response to follicle-stimulating hormone (FSH), and progesterone after ovulation in response to luteinizing hormone (LH).)

2024-09-25 14:24 UTC, Caroline-99 approved these changes

2024-09-25 14:31 UTC, merged