Fixes #2528 - NTRs - externa and interna theca cells
obophenotype/cell-ontology pull request #2622
Opened 2024-09-30 12:05 UTC by Caroline-99

Fixes #2528

-Added two new terms - interna and exerna theca cells 
-Added textual, logical defs, references and synonyms -imported uberon terms
-revised the logical and textual defs of theca cell

2024-09-30 12:14 UTC, aleixpuigb commented
#gogoeditdiff

2024-09-30 12:30 UTC, Caroline-99 commented
#gogoeditdiff

2024-10-01 10:58 UTC, aleixpuigb requested changes
Please, see inline comments

2024-10-01 10:58 UTC, aleixpuigb commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "MESH:D013799") Annotation(oboInOwl:hasDbXref "PMID:36758341") Annotation(oboInOwl:hasDbXref "doi:/10.1016/j.biocel.2005.01.016") obo:IAO_0000115 obo
For doi:/10.1016/j.biocel.2005.01.016 you can use the PMID:15833266

2024-10-01 10:58 UTC, aleixpuigb commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:31320652") Annotation(oboInOwl:hasDbXref "PMID:32530882") Annotation(oboInOwl:hasDbXref "Wikipedia:Theca_interna") Annotation(oboInOwl:hasDbXre
For doi:/10.1016/j.biocel.2005.01.016 you can use the PMID:15833266

2024-10-01 10:58 UTC, aleixpuigb commented on src/ontology/cl-edit.owl
> +SubClassOf(obo:CL_4052013 obo:CL_0002320)
This is not needed since it is inherited (theca cell is a stromal cell, which is a connective tissue cell)

2024-10-01 12:13 UTC, aleixpuigb approved these changes

2024-10-01 12:14 UTC, merged