Fixes #2481 NTR- choroid plexus capillary endothelial cell
obophenotype/cell-ontology pull request #2629
Opened 2024-10-01 11:45 UTC by Caroline-99

Fixes #2481 

Added a new term with logical and textual defs and references

2024-10-01 11:57 UTC, Caroline-99 commented
#gogoeditdiff

2024-10-09 17:24 UTC, dosumis requested changes

2024-10-09 17:24 UTC, dosumis commented on src/ontology/cl-edit.owl
> +EquivalentClasses(obo:CL_4052017 ObjectIntersectionOf(obo:CL_0002144 ObjectSomeValuesFrom(obo:BFO_0000050 obo:UBERON_0005206)))
should be part of 'choroid plexus', not 'choroid plexus stroma' which is defined as "Stromal matrix _surrounding_ blood vessels within the choroid plexus"

2024-10-10 09:43 UTC, Caroline-99 commented
#gogoeditdiff

2024-10-10 14:03 UTC, dosumis commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:18480313") Annotation(oboInOwl:hasDbXref "PMID:32375819") Annotation(oboInOwl:hasDbXref "https://www.ncbi.nlm.nih.gov/books/NBK27998/") obo:IAO
Text def still says choroid plexus stroma.  Otherwise now good.

2024-10-10 14:41 UTC, dosumis approved these changes

2024-10-11 07:54 UTC, dosumis approved these changes

2024-10-11 08:18 UTC, merged