Update cl-edit.owl
obophenotype/cell-ontology pull request #2674
Opened 2024-10-17 21:28 UTC by dosumis

- Mesothelial cells of gut now part of serosa
- tidying up partonomy for intestinal lining
- Fixed brush border on enteroycte

2024-10-17 21:28 UTC, dosumis commented
#gogoeditdiff

2024-10-17 21:40 UTC, dosumis commented
Diffs are a bit odd.  Maybe some edits bleeding in from Master?

2024-11-19 12:45 UTC, Caroline-99 commented
#gogoeditdiff

2024-11-21 11:31 UTC, Caroline-99 commented
#gogoeditdiff

2024-12-05 10:48 UTC, Caroline-99 commented
#gogoeditdiff

2024-12-05 11:11 UTC, Caroline-99 commented
#gogoeditdiff

2024-12-05 11:34 UTC, Caroline-99 commented
@aleixpuigb @dosumis This PR is ready for review, and all conflicts have been resolved. I am not sure why gogoeditdiff is not showing the latest updates (ie. this should be **EquivalentTo**`'mesothelial cell' and ('part of' some 'serosa of small intestine') `  and **SubclassOf** `'part of' some 'epithelium of small intestine')`

![image](https://github.com/user-attachments/assets/73055458-97d7-4833-bc7a-02fd4e0182f0)

2024-12-06 15:25 UTC, Caroline-99 commented
#gogoeditdiff

2024-12-06 15:27 UTC, Caroline-99 commented
Some additional changes were made to this PR during my meeting with @dosumis this morning.

2024-12-09 13:37 UTC, aleixpuigb requested changes
Some inferences gave been lost:
- early colonocyte -> colonocyte

2024-12-09 14:37 UTC, dosumis commented on src/ontology/cl-edit.owl
> +EquivalentClasses(obo:CL_0011108 ObjectIntersectionOf(obo:CL_0000066 ObjectSomeValuesFrom(obo:BFO_0000050 obo:UBERON_0000397)))
Fixed

2024-12-10 10:17 UTC, aleixpuigb approved these changes

2024-12-11 16:02 UTC, merged