Fixes #2672 - textual and logical defs - parietal cell
obophenotype/cell-ontology pull request #2681
Opened 2024-10-18 12:13 UTC by Caroline-99

- Revised textual defintion and add extra information in the comments section
- Revised logical defs (Added + Updated GO links) + added links to uberon 
- Added references

2024-10-18 13:16 UTC, Caroline-99 commented
#gogoeditdiff

2024-10-24 09:56 UTC, JABelfiore requested changes
'fundic gastric gland' doesn't appear to be a commonly used term, please change to gastric gland (refers to glands in all parts of stomach)or fundic gland (refers to gland specifically in the fundus of the stomach). Everything else looks great!

2024-10-24 10:38 UTC, JABelfiore commented
> > 'fundic gastric gland' doesn't appear to be a commonly used term, please change to gastric gland (refers to glands in all parts of stomach)or fundic gland (refers to gland specifically in the fundus of the stomach). Everything else looks great!
> 
> @JABelfiore I have just checked and there is no an uberon term for fundic gland. Fundic gland is used as a synonym to fundic gastric gland in Uberon and is defined as `The fundus glands (or fundic glands, or gastric glands) are found in the body and fundus of the stomach. They are simple tubes, two or more of which open into a single duct`. Would you be okay with me using the term [fundic gastric gland](http://purl.obolibrary.org/obo/UBERON_0010038)? Or do you want me to change it to gastric gland ?

If its in uberon happy to keep as is

2024-10-24 10:38 UTC, JABelfiore approved these changes

2024-10-24 10:39 UTC, merged