Fixes #2673 NTR CxG type IIx muscle cell
obophenotype/cell-ontology pull request #2731
Opened 2024-11-05 12:26 UTC by aleixpuigb

Fixes #2673 NTR CxG type IIx muscle cell
This PR solves problems of #2729

2024-11-05 12:35 UTC, Caroline-99 commented
#gogoeditdiff

2024-11-08 11:52 UTC, AvolaAmg requested changes

2024-11-08 11:52 UTC, AvolaAmg commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:34727990") oboInOwl:hasExactSynonym obo:CL_4052026 "type 2x muscle cell")
Consider adding the synonym: type 2x fiber 
from PMID: [34727990](https://pubmed.ncbi.nlm.nih.gov/34727990/)

2024-11-08 11:52 UTC, AvolaAmg commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:34727990") rdfs:comment obo:CL_4052026 "In humans, type IIx fiber contains high levels of MYLK2, enhancing contraction speed and force via myos
Consider adding in the extended description what are these fibers known for: sarcopenia, diabetes/obesity and Duchenne muscular dystrophy.
Apparently in loss of muscle fibres due to aging (sarcopenia) type 2x fibers are the ones that are missing the most
https://doi.org/10.1016/j.exger.2020.111171
PMID: 15462613
PMID: [27199166](https://pubmed.ncbi.nlm.nih.gov/27199166/)
also from this reference PMID: [27199166](https://pubmed.ncbi.nlm.nih.gov/27199166/) type 2x fibers increase in proportion in diabetes type 2 and obesity and they are the first one to degenerate during Duchenne Muscular Dystrophy.

2024-11-08 11:52 UTC, AvolaAmg commented
Please see in line comments!

2024-11-08 13:02 UTC, Caroline-99 commented
#gogoeditdiff

2024-11-08 15:25 UTC, AvolaAmg approved these changes
All good! thanks for addressing the comments

2024-11-08 15:26 UTC, merged