adjust-the-hierarchy-CNS-nematoda-and-CNS-vertebrata
obophenotype/cell-ontology pull request #2745
Opened 2024-11-08 13:29 UTC by AvolaAmg

Fixes #2654

2024-11-08 15:27 UTC, AvolaAmg commented
#gogoeditdiff

2024-11-08 16:33 UTC, Caroline-99 requested changes

2024-11-08 16:33 UTC, Caroline-99 commented on src/ontology/cl-edit.owl
> -EquivalentClasses(obo:CL_2000031 ObjectIntersectionOf(obo:CL_0000540 ObjectSomeValuesFrom(obo:RO_0002100 obo:UBERON_2000120)))
Removing this axiom resulted in the anterior and posterior lateral line ganglion neurons no longer being inferred as subclasses of lateral line ganglion neurons.

To fix this - you need to change the axioms of both the anterior and posterior lateral line ganglion neurons to align with the new logical definition of  lateral line ganglion neuron 

ie.
<img width="489" alt="image" src="https://github.com/user-attachments/assets/9db23e82-7df6-4692-8fc6-76ec608df6a0">

2024-11-13 11:57 UTC, AvolaAmg commented
#gogoeditdiff

2024-11-13 13:50 UTC, merged