Addresses #2786 NTR CD57-positive enterocyte
obophenotype/cell-ontology pull request #2847
Opened 2024-12-06 16:05 UTC by aleixpuigb

Fixes #2786 NTR CD57-positive enterocyte

2024-12-06 16:06 UTC, aleixpuigb commented
#gogoeditdiff

2024-12-06 16:34 UTC, aleixpuigb commented
CellMark comments have been imported when refreshing the imports, causing that some terms have two comments and failing the QC (I might be wrong on the assessment, please correct me if I am wrong). We might need a different AP to avoid having this problem.
CC @hkir-dev @gouttegd @Caroline-99

2024-12-06 18:18 UTC, gouttegd commented
> causing that some terms have two comments and failing the QC (I might be wrong on the assessment, please correct me if I am wrong)

Your assessment looks correct to me.

Looking at the CellMarks comments:

> * The marker set C1orf194, MS4A8 can identify the Human cell type ciliated columnar cell of tracheobronchial tree in the Lung with a confidence of 0.86 (NS-Forest FBeta value).
> * The marker set SST, PLCH1 can identify the Human cell type sst GABAergic cortical interneuron in the Brain with a confidence of 0.842367005 (NS-Forest FBeta value).
> * The marker set MSR1, FABP4 can identify the Human cell type alveolar macrophage in the Lung with a confidence of 0.80 (NS-Forest FBeta value).

It seems to me that such an information should rather belong to a dedicated annotation. Using `rdfs:comment` as a “joker” annotation to store any kind of structured data (such as a confidence score) is never a good idea.

If we can’t get the CellMarks folks to change that we might have to strip `rdfs:comment` annotations from the CLM component when we update it.

2024-12-10 11:32 UTC, dosumis commented
> Using rdfs:comment as a “joker” annotation to store any kind of structured data (such as a confidence score) is never a good idea.

The idea was to add markers and confidence scores in human readable form to go along with a formal specification  - including marker IRIs and confidence scores as floats.  The one comment restriction is an annoying OBO legacy.  My ideal solution would be to add SPARQL update to the pipeline to concatenate comments.  @gouttegd  - what's your opinion on this option? (I have a feeling you might object.)

2024-12-10 14:09 UTC, gouttegd commented
> what's your opinion on this option? (I have a feeling you might object.)

I am certainly not very fond of it. That being said, it’s not like I had anything much better to propose…

(A truly ideal solution for me would be, either: (1) use dedicated annotation properties for confidence scores and marker IRIs, and leave it to the ontology browser(s) to display those informations in a human-friendly form, or (2) get rid of the OBO format and its limitations entirely. Neither of which are really under our control.)

But adding a step in the pipeline to merge comments could be quite tricky as it involves comments spread over several files…

How about merging comments, but _only_ for OBO artefacts?

2024-12-10 14:28 UTC, dosumis commented
> How about merging comments, but only for OBO artefacts?

Works for me.

2024-12-10 15:48 UTC, gouttegd commented
> (Although breaking OBO<->OWL round-tripping makes me a bit queasy)

Pretty sure that horse has already left the barn… CL contains axioms that are not representable in OBO and that are rendered in the `owl-axioms` header tag, but we forcefully strip that tag when generating the OBO products, which therefore already do not contain the same contents as the products in other formats.

2024-12-20 11:23 UTC, Caroline-99 commented
#gogoeditdiff

2024-12-20 15:31 UTC, Caroline-99 requested changes

2024-12-20 15:31 UTC, Caroline-99 commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:37468586") rdfs:comment obo:CL_4033092 "While CD57 is traditionally associated with immune cells (e.g., NK cells), its expression on enterocyte
Everything looks good. There is only a typo in the comments section - should have a space here `speciallyenriched`

2024-12-20 15:48 UTC, Caroline-99 approved these changes

2024-12-20 15:58 UTC, merged