stomach smooth muscle circular layer cell
obophenotype/cell-ontology pull request #2849
Opened 2024-12-09 10:46 UTC by JABelfiore

def and refs added

2024-12-16 15:22 UTC, dosumis requested changes
Looks good, just needs EC def.

2024-12-16 15:22 UTC, dosumis commented on src/ontology/cl-edit.owl
> +SubClassOf(obo:CL_4047036 obo:CL_4047034)
Make EquivalentClass Def (smooth muscle and part_of some 'stomach smooth muscle circular layer')

2024-12-16 15:23 UTC, dosumis commented
We also need a general grouping term for circular layer smooth muscle cell.  Could be added in another PR or here.

2025-02-21 13:30 UTC, dosumis commented
#gogoeditdiff

2025-03-07 15:21 UTC, JABelfiore commented
#gogoeditdiff

2025-03-13 16:16 UTC, dosumis approved these changes

2025-03-13 16:16 UTC, merged