Fixes #2855 NTR limbal epithelial stem cell
obophenotype/cell-ontology pull request #2857
Opened 2024-12-11 16:07 UTC by aleixpuigb

Fixes #2855 NTR limbal epithelial stem cell

2024-12-11 16:08 UTC, aleixpuigb commented
Unfortunately the branch was not created from master.

2024-12-16 14:56 UTC, dosumis requested changes

2024-12-16 14:56 UTC, dosumis commented on src/ontology/cl-edit.owl
> +EquivalentClasses(obo:CL_4033093 ObjectIntersectionOf(obo:CL_0000034 ObjectSomeValuesFrom(obo:BFO_0000050 obo:UBERON_0006761)))
Should be "epithelial fate stem cell", either by direct assertion or inference.

2024-12-17 10:55 UTC, Caroline-99 approved these changes

2024-12-17 12:07 UTC, merged