dogiel type I mesenteric neuron
obophenotype/cell-ontology pull request #2864
Opened 2024-12-16 14:53 UTC by JABelfiore

Dogiel type I neuron

A multipolar neuron in the myenteric plexus of the gastrointestinal tract, characterized by a small to medium-sized cell bodyband multiple short dendrites. This cell functions as motor neurons or interneurons, often containing choline acetyltransferase and other neurotransmitters. This neuron exhibits fast excitatory postsynaptic potentials and can be classified into stubby and spiny subtypes based on dendritic morphology.
doi.org/10.1038/s41575-020-0271-2
 https://doi.org/10.1038/s41575-021-00561-y

PMID: [32152479](https://pubmed.ncbi.nlm.nih.gov/32152479/)
PMID: [34170401](https://pubmed.ncbi.nlm.nih.gov/34170401/)

Part of UBERON:0002439 myenteric nerve plexus

Parent term: multipolar neuron

2025-02-07 09:33 UTC, AvolaAmg commented
#gogoeditdiff

2025-02-21 13:43 UTC, dosumis requested changes
> A multipolar neuron in the myenteric plexus of the gastrointestinal tract, characterized by a small to medium-sized cell bodyband multiple short dendrites. This cell functions as motor neurons or interneurons, often containing choline acetyltransferase and other neurotransmitters. This neuron exhibits fast excitatory postsynaptic potentials and can be classified into stubby and spiny subtypes based on dendritic morphology.

- Fix typo.
- remove second sentence
- Add in-line refs to support assertions in last sentence

2025-03-07 15:11 UTC, dosumis requested changes
Content all looks good, but needs location.  Use either 'part of' or 'has soma located in'.  Latter is needed if neuron projects outside the region you are linking.

2025-03-07 15:14 UTC, dosumis approved these changes

2025-03-07 15:33 UTC, merged