Update cl-edit.owl
obophenotype/cell-ontology pull request #843
Opened 2021-01-15 11:16 UTC by dosumis

Fixes #738

2021-01-15 11:19 UTC, shawntanzk requested changes
Needs more information

2021-01-15 11:19 UTC, shawntanzk commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "WikipediaVersion:Gamma_motor_neuron&oldid=906640465") obo:IAO_0000115 obo:CL_0008037 "A lower motor neuron that innervates only intrafusal muscle fi
Add more information

2021-01-15 12:56 UTC, dosumis commented
@shawntanzk  - can you look in to adding some more recent references on gamma neurons. I'd especially like some refs (maybe text book?) that back up the statements about function.

2021-01-15 14:21 UTC, shawntanzk commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "DOI:10.1093/acprof:oso/9780195159561.001.1") Annotation(oboInOwl:hasDbXref "WikipediaVersion:Gamma_motor_neuron&oldid=906640465") obo:IAO_0000115 ob
Is this how you add a DOI? the manual came with PMID, this only has a DOI or ISBN-13

2021-01-15 14:28 UTC, dosumis commented
DOI is fine.  Format is correct.  Build fail on travis is due to us hitting data limits.  Now fixed & re-running.

2021-01-15 15:24 UTC, shawntanzk commented
Oh was just doing a whole google on what the issue was, is it ok now? I thought it came down to my Docker not running well as I couldn't do the file sharing part, as I couldn't access it, as I couldn't access hyper-V, as I'm using windows home version (It was a lot of googling haha). If it's all ok, happy to add more stuff in. On that note, how does the cell ontology repository deal with species? - most of my readings on lower motor neurons (esp on transcriptomics) are mouse based.

2021-01-19 07:42 UTC, shawntanzk approved these changes

2021-01-19 22:15 UTC, merged