Added Vip GABAergic Interneuron
obophenotype/cell-ontology pull request #895
Opened 2021-01-26 14:34 UTC by shawntanzk

Fixes #866

2021-01-27 01:38 UTC, patrick-lloyd-ray approved these changes

2021-01-27 08:37 UTC, dosumis requested changes
see note on def

2021-01-27 08:37 UTC, dosumis commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "PMID:33186530") obo:IAO_0000115 obo:CL_4023016 "A GABAergic neuron that expresses vasoactive intestinal polypeptide")
Text def should mention cortical location

2021-01-27 17:09 UTC, patrick-lloyd-ray approved these changes

2021-01-29 13:35 UTC, dosumis approved these changes

2021-01-31 10:46 UTC, merged