Added L6b glutamatergic neuron
obophenotype/cell-ontology pull request #951
Opened 2021-02-18 10:22 UTC by shawntanzk

Fixes #881
!Note: CL_4023009 taken in #934 -> fix this before merging!

2021-02-19 20:48 UTC, patrick-lloyd-ray commented on src/ontology/cl-edit.owl
> +AnnotationAssertion(Annotation(oboInOwl:hasDbXref "DOI:10.1101/2020.10.19.34312") Annotation(oboInOwl:hasDbXref "PMID:30382198") obo:IAO_0000115 obo:CL_4023038 "Glutamatergic neuron located in cortic
Small changes: "A glutamatergic neuron located in cortical layer 6b. They are transcriptomically related to corticothalamic-projecting neurons but have differential projections to the thalamus or anterior cingulate."

2021-02-19 20:48 UTC, patrick-lloyd-ray reviewed
Small changes.

2021-03-11 12:52 UTC, dosumis requested changes
Agree with Patrick's suggested changed to def.

2021-03-11 13:09 UTC, shawntanzk reviewed
> Agree with Patrick's suggested changed to def.

Have already changed it accordingly

2021-03-22 09:02 UTC, dosumis approved these changes

2021-03-22 09:11 UTC, merged